// 1 getting input from  user - Cal and dis
// an object of food items

const bp = [
  {
    type: 'BREAKFAST',
    itemid: 1,
    name: '2 stuffed Cabbage Chapati with 1/2 cup of cucumber raita and 1 tablespoon of tomato chutney',
    cal: ' 327Cal',
    carb: ' 44.08g',
    protein: ' 14.23g',
    fat: '11.23g',
    path: 'ccparatha.jpeg',
    path2: 'cucumber.jpg',
  },
  {
    type: 'BREAKFAST',
    itemid: 2,
    name: 'Cornflakes and milk with strawberries(3 to 4)and 4 almonds',
    cal: '234Cal',
    carb: ' 35.35g',
    protein: ' 7.4g',
    fat: '7.43g',
    path: 'cornflakes.jpeg',
    path2: 'almonds.jpeg',
  },
  {
    type: 'BREAKFAST',
    itemid: 3,
    name: '2 Rice Dosa with ½ cup Sambar and 1 teaspoon Mint chutney',
    cal: ' 342Cal',
    carb: ' 37.8g',
    protein: '5.7g',
    fat: '16.1g',
    path: 'dosa.jpeg',
    path2: 'sambar.jpeg',
  },
  {
    type: 'BREAKFAST',
    itemid: 4,
    name: '2 Aloo paratha with 2 tablespoon Tomato Onion raita',
    cal: ' 432Cal',
    carb: ' 52g',
    protein: ' 9g',
    fat: '22.26g',
    path: 'aloopar.jpeg',
    path2: 'raita.jpeg',
  },

  {
    type: 'LUNCH',
    itemid: 1,
    name: '1/2 cup Chicken curry and 2 Chapati',
    cal: ' 280Cal ',
    carb: ' 28g',
    protein: ' 30g',
    fat: '5g',
    path: 'chickcur.jpeg',
    path2: 'ch.jpg',
  },
  {
    type: 'LUNCH',
    itemid: 2,
    name: '1/2 cup Cauliflower curry and one cup Rice flakes pulao',
    cal: ' 475Cal ',
    carb: ' 101g',
    protein: ' 9.19g',
    fat: '6.76g',
    path: 'cauliflower.jpeg',
    path2: 'riceflake.jpeg',
  },
  {
    type: 'LUNCH',
    itemid: 3,
    name: '1 cup Rice with ½ cup Yam curry and 1 glass of Butter milk',
    cal: ' 502Cal',
    carb: ' 57.2g',
    protein: ' 44.4g',
    fat: '6.4g',
    path: 'yam.jpeg',
    path2: 'buttermilk.jpeg',
  },
  {
    type: 'LUNCH',
    itemid: 4,
    name: '4 Chapati with 1 cup cauliflower, peas and potato sabji',
    cal: ' 484Cal',
    carb: ' 80.7g',
    protein: '17.1 g',
    fat: '11.9g',
    path: 'ch.jpg',
    path2: 'potato.jpeg',
  },
  {
    type: 'DINNER',
    itemid: 1,
    name: '2 Chapati with 1/2 cup Ridge gourd curry',
    cal: ' 204Cal',
    carb: ' 36.8g',
    protein: ' 4.8g',
    fat: '4.8g',
    path: 'ch.jpg',
    path2: 'ridge.jpg',
  },
  {
    type: 'DINNER',
    itemid: 2,
    name: '1 cup vegetable soup with 2 Moong dal dosa and 2 tablespoon Mint Coriander Chutney',
    cal: ' 210Cal',
    carb: ' 70g',
    protein: ' 22g',
    fat: ' 2g',
    path: 'moong dos.jpg',
    path2: 'greenc.jpg',
  },
  {
    type: 'DINNER',
    itemid: 3,
    name: '1 cup Bean and Barley soup',
    cal: ' 208Cal',
    carb: ' 34g',
    protein: ' 11g',
    fat: '3g',
    path: 'rajma.jpeg',
    path2: 'barley.jpeg',
  },
  {
    type: 'DINNER',
    itemid: 4,
    name: '1 cup Pea and Spinach Carbonara',
    cal: ' 430Cal',
    carb: ' 54g',
    protein: ' 20g',
    fat: '15g',
    path: 'pea.jpeg',
    path2: 'spinach.jpeg',
  },

  {
    type: 'SNACK',
    itemid: 1,
    name: 'Roasted Chana(40 g)with 1 cup of Herbal tea',
    cal: ' 159Cal',
    carb: ' 28g',
    protein: ' 5g',
    fat: '3g',
    path: 'chana.jpeg',
    path2: 'herbal.jpeg',
  },
  {
    type: 'SNACK',
    itemid: 2,
    name: '1 glass of Carrot juice with one cup of Sprouts',
    cal: ' 244Cal',
    carb: ' 35g',
    protein: ' 10g',
    fat: '7g',
    path: 'carrot.jpeg',
    path2: 'sproutsal.jpeg',
  },
  {
    type: 'SNACK',
    itemid: 3,
    name: 'Unsalted puffed rice with 1 cup of Coffee',
    cal: ' 89Cal',
    carb: ' 16g',
    protein: ' 3.3g',
    fat: '1.2g',
    path: 'puffr.jpeg',
    path2: 'coffee.jpeg',
  },
  {
    type: 'SNACK',
    itemid: 4,
    name: '1 Banana with 4 strawberries and yogurt',
    cal: ' 177Cal',
    carb: ' 41g',
    protein: ' 6g',
    fat: '0.2g',
    path: 'banstra.jpeg',
    path2: 'yog.jpeg',
  },
];
module.exports = bp;
// mdule.exports = breathingproblem;
// / moule.exports = diab
