const breathingproblem = [
  {
    type: 'BREAKFAST',
    itemid: 1,
    name: 'Corn Flakes with apple',
    cal: '152Cal',
    carb: '38g',
    protien: '2.3g',
    fat: '1.17g',
    path: 'cornflakesss.jpg',
    path2: 'apple.jpg',
  },
  {
    type: 'BREAKFAST',
    itemid: 2,
    name: '2 veg Sandwich with Orange Juice',
    cal: '248 Cal',
    carb: '18g',
    protien: '8g',
    fat: '6g',
    path:'vegsandwich.jpg',
    path2:'orangejuice.jpg',
  },
  {
    type: 'BREAKFAST',
    itemid: 3,
    name: 'Boiled Veg Salad with Apple',
    cal: ' 102 Cal',
    carb: ' 19g',
    protien: '2g',
    fat: '3g',
    path:'vegsalad.jpg',
    path2:'apple.jpg',
  },
  {
    type: 'BREAKFAST',
    itemid: 4,
    name: '2 Veg Sandwich with Pomegranate Juice',
    cal: ' 265 cal',
    carb: ' 30g',
    protien: '12g',
    fat: ' 1g',
    path:'vegsandwich.jpg',
    path2:'pomegranatejuice.jpg',
  },

  {
    type: 'LUNCH',
    itemid: 1,
    name: '1 cup brown rice- dal with Cabbage',
    cal: ' 3275cal ',
    carb: ' 64g',
    protien: '14g',
    fat: '4',
    path:'brownrice.jpg',
    path2:'dal.jpg',
  },
  {
    type: 'LUNCH',
    itemid: 2,
    name: '1 cup brown rice with Veg curry ',
    cal: '350cal ',
    carb: '47g',
    protien:'9g',
    fat: '7g',
    path:'brownrice.jpg',
    path2:'vegcurry.jpg',
  },
  {
    type: 'LUNCH',
    itemid: 3,
    name: '1 cup brown rice with pepper chicken',
    cal: ' 290cal',
    carb: ' 34g',
    protien: '22g',
    fat: '7g',
    path:'brownrice.jpg',
    path2:'pepperchicken.jpg',
  },
  {
    type: 'LUNCH',
    itemid: 4,
    name: '1 cup brown rice with beetroot',
    cal: '186cal',
    carb: '32g',
    protien: '3g',
    fat: '1g',
    path:'brownrice.jpg',
    path2:'beetroot.jpg',
  },
  {
    type: 'DINNER',
    itemid: 1,
    name: '2 Multigrain Chappathi - Cauliflower curry',
    cal: '241cal',
    carb: '44.5g',
    protien: '10.3g',
    fat: '14.1g',
    path:'ch.jpg',
    path2:'cauliflower.jpeg',
  },
  {
    type: 'DINNER',
    itemid: 2,
    name: '2 Multigrain Chappathi - with chicken stew',
    cal: ' 561cal',
    carb: '41g',
    protien:'38g',
    fat: '17g',
    path:'ch.jpg',
    path2:'chickenstew.jpg',
  },
  {
    type: 'DINNER',
    itemid: 3,
    name: '1 cup brown rice with salmon',
    cal: ' 250cal',
    carb: '32g',
    protien: '22g',
    fat: '4g',
    path:'brownrice.jpg',
    path2:'salmon.jpeg',
  },
  {
    type: 'DINNER',
    itemid: 4,
    name: '1 cup brown rice with carrot',
    cal: ' 191cal',
    carb: ' 42g',
    protien: '4g',
    fat: '1g',
    path:'brownrice.jpg',
    path2:'carrotdish.jpg',
  },

  {
    type: 'SNACK',
    itemid: 1,
    name: 'Almonds with strawberries',
    cal: ' 186cal',
    carb: '9g',
    protien: '4g',
    fat: '17g',
    path:'almonds.jpeg',
    path2:'strawberry.jpg',
  },
  {
    type: 'SNACK',
    itemid: 2,
    name: 'Veg salad with green tea',
    cal: ' 40cal',
    carb: '5g',
    protien: '1g',
    fat: '2g',
    path:'vegsalad.jpg',
    path2:'greent.jpg',
  },
  {
    type: 'BEVERAGE',
    itemid: 3,
    name: 'green tea with almonds',
    cal: ' 178cal',
    carb: '5g',
    protien: '4g',
    fat: '17g',
    path:'greent.jpg',
    path2:'almonds.jpeg',
  },
  {
    type: 'SNACK',
    itemid: 4,
    name: 'veg soup with roasted chana',
    cal: ' 345cal',
    carb: '51g',
    protien: '10g',
    fat: '9g',
    path:'vegsoup.jpg',
    path2:'chana.jpeg',
  },
];
module.exports = breathingproblem;
