// 1 getting input from  user - Cal and dis
// an object of food items

const card = [
  {
    type: 'BREAKFAST',
    itemid: 1,
    name: 'Mixed Veg Poha with sprouts and Apple',
    cal: ' 130Cal',
    carb: ' 27g',
    protien: ' 2.6g',
    fat: '2g',
    path: 'poha.png',
    path2: 'sproutsal.jpeg',
  },
  {
    type: 'BREAKFAST',
    itemid: 2,
    name: '2 Multigrain veg Sandwich with Panner veg toast',
    cal: '235 Cal',
    carb: ' 25.2g',
    protien: ' 4.5g',
    fat: '1.7g',
    path: 'mul.jpeg',
    path2: 'pannersan.jpeg',
  },
  {
    type: 'BREAKFAST',
    itemid: 3,
    name: 'Oat Meal with Apple and Pomegranate',
    cal: ' 165 Cal',
    carb: ' 51g',
    protien: '5g',
    fat: '3g',
    path: ' oats.jpeg',
    path2: 'oat2.jpeg',
  },
  {
    type: 'BREAKFAST',
    itemid: 4,
    name: '2 dosas with sambar and peanut chutney',
    cal: ' 178 cal',
    carb: ' 61g',
    protien: ' 12g',
    fat: '0.7g',
    path: ' dosa.jpeg',
    path2: 'peanutc.jpeg',
  },

  {
    type: 'LUNCH',
    itemid: 1,
    name: '1 cup brown rice- dal- steamed carrots and beans raita',
    cal: ' 367cal ',
    carb: ' 50g',
    protien: ' 15.54g',
    fat: '7.96',
    path: ' brownrice.jpg',
    path2: 'carbean.jpeg',
  },
  {
    type: 'LUNCH',
    itemid: 2,
    name: '2 multi-grain roti - palak paneer -onion tomato raita',
    cal: ' 342cal ',
    carb: ' 112g',
    protien: ' 28g',
    fat: '45.4g',
    path: ' multiro.jpg',
    path2: 'palak.jpeg',
  },
  {
    type: 'LUNCH',
    itemid: 3,
    name: 'Veg Pulav and Panner Masala',
    cal: ' 600cal',
    carb: ' 61g',
    protien: ' 21g',
    fat: '50g',
    path: ' pulav.jpeg',
    path2: 'pan.jpeg',
  },
  {
    type: 'LUNCH',
    itemid: 4,
    name: '3 Phulkas - Dal tadka -Veggies',
    cal: ' 551cal',
    carb: ' 101g',
    protien: '23.2 g',
    fat: '10.8g',
    path: ' ch.jpg',
    path2: 'dal.jpg',
  },
  {
    type: 'DINNER',
    itemid: 1,
    name: '2 Multigrain Chappathi - Cauliflower/Cabbage curry',
    cal: ' 241cal',
    carb: ' 44.5g',
    protien: ' 10.3g',
    fat: '14.1g',
    path: ' ch.jpg',
    path2: 'cauliflower.jpeg',
  },
  {
    type: 'DINNER',
    itemid: 2,
    name: '1 cup brown rice with rajma sabzi',
    cal: '654cal ',
    carb: ' 88g',
    protien: ' 17.7',
    fat: '12.6g',
    path: ' brownrice.jpg',
    path2: 'rajma.jpeg',
  },
  {
    type: 'DINNER',
    itemid: 3,
    name: 'Jerra Rice -Gobi Sabzi Dal',
    cal: ' 484 cal',
    carb: ' 52g',
    protien: ' 15g',
    fat: '13g',
    path: ' jeera.jpeg',
    path2: 'gobi.jpeg',
  },
  {
    type: 'DINNER',
    itemid: 4,
    name: '2 Millet Roti 1 bowl dal with methi ',
    cal: ' 358cal',
    carb: ' 60.7g',
    protien: ' 12.1g',
    fat: '4.6g',
    path: ' miletr.jpeg',
    path2: 'dal.jpg',
  },

  {
    type: 'SNACK',
    itemid: 1,
    name: 'ButterMilk - 2 Wheat biscuits',
    cal: ' 233cal',
    carb: ' 38g',
    protien: ' 13g',
    fat: '3g',
    path: ' buttermilk.jpeg',
    path2: 'wheatbisc.jpg',
  },
  {
    type: 'SNACK',
    itemid: 2,
    name: ' Roasted chana and peanuts - Curd ',
    cal: ' 264cal',
    carb: ' 32g',
    protien: ' 15g',
    fat: '10g',
    path: ' chana.jpeg',
    path2: 'curd.jpeg',
  },
  {
    type: 'SNACK',
    itemid: 3,
    name: 'Flax seeds 1spn with Sprout Salad',
    cal: ' 72cal',
    carb: ' 14g',
    protien: ' 5g',
    fat: '1g',
    path: ' flax.jpg',
    path2: 'sproutsal.jpeg',
  },
  {
    type: 'SNACK',
    itemid: 4,
    name: '1 plate cut cucumber– 2 multi-grain crackers',
    cal: ' 190cal ',
    carb: ' 24g',
    protien: ' 4g',
    fat: '9g',
    path: ' cucumber.jpg',
    path2: 'mulc.jpg',
  },
];
module.exports = card;
// mdule.exports = breathingproblem;
// / moule.exports = diab
