const diabetes = [
  {
    type: 'BREAKFAST',
    itemid: 1,
    name: 'Broken Wheat Upma – 1 cup with Green chutney 1 tablespoon',
    cal: ' 123Cal',
    carb: ' 19.7g',
    protein: ' 2.8g',
    fat: '3.7g',
    path: 'upma.jpeg',
    path2: 'greenc.jpg',
  },
  {
    type: 'BREAKFAST',
    itemid: 2,
    name: 'Millet Dosa – 2 with Sambar -1/2 cup',
    cal: '231 Cal',
    carb: ' 31g',
    protein: ' 7g',
    fat: '2g',
    path: 'mild.jpeg',
    path2: 'sambar.jpeg',
  },
  {
    type: 'BREAKFAST',
    itemid: 3,
    name: '1 piece of brown bread with 2 boiled egg whites and 1 cup green tea',
    cal: ' 131 Cal',
    carb: ' 26g',
    protein: '6g',
    fat: '0.3g',
    path: 'upma.jpeg',
    path2: 'greent.jpg',
  },
  {
    type: 'BREAKFAST',
    itemid: 4,
    name: '1 cup red rice vegetable poha with 1/2  cup boiled sprouts',
    cal: ' 382.5 cal',
    carb: ' 87g',
    protein: ' 7g',
    fat: '0.5g',
    path: 'poha.png',
    path2: 'sproutsal.jpeg',
  },

  {
    type: 'LUNCH',
    itemid: 1,
    name: '2 millet rotis with 1 bowl carrot and beans stir fry and 1/4 cucumber raita',
    cal: ' 271cal ',
    carb: ' 66.05g',
    protein: ' 13.65g',
    fat: '19.1g',
    path: 'miletr.jpeg',
    path2: 'carbean.jpeg',
  },
  {
    type: 'LUNCH',
    itemid: 2,
    name: 'Phulka(no ghee) – 2 with Dal 1 cup and Bitter gourd with Egg 1 cup',
    cal: ' 468cal ',
    carb: ' 71g',
    protein: ' 20g',
    fat: '14g',
    path: 'phulka.jpeg',
    path2: 'dal.jpg',
  },
  {
    type: 'LUNCH',
    itemid: 3,
    name: '1 ½ cups of cooked brown rice with 1/2 cup of dal and 1 cup of stir – fried vegetables',
    cal: ' 447cal',
    carb: ' 79.5g',
    protein: ' 18g',
    fat: '9g',
    path: 'brownrice.jpg',
    path2: 'dal.jpg',
  },
  {
    type: 'LUNCH',
    itemid: 4,
    name: 'Salmon salad with Cannelini beans',
    cal: ' 493cal',
    carb: ' 53g',
    protein: '38g',
    fat: '15g',
    path: 'salmon.jpeg',
    path2: 'cbean.jpg',
  },
  {
    type: 'DINNER',
    itemid: 1,
    name: '2 rotis – 1 cup dal with mixed vegetables',
    cal: ' 280cal',
    carb: ' 6g',
    protein: ' 8g',
    fat: '0.8g',
    path: 'salmon.jpeg',
    path2: 'cbean.jpg',
  },
  {
    type: 'DINNER',
    itemid: 2,
    name: 'Chapati – 1 with Palak  sabji – 2 katori',
    cal: ' 202cal',
    carb: ' 37g',
    protein: ' 7g',
    fat: '3.4g',
    path: 'ch.jpg',
    path2: 'palaks.jpg',
  },
  {
    type: 'DINNER',
    itemid: 3,
    name: 'Mixed vegetable Daliya – 1 cup with mint chutney – 2 tablespoon',
    cal: ' 125 cal',
    carb: ' 23g',
    protein: ' 7g',
    fat: '1.3g',
    path: 'vegd.jpeg',
    path2: 'greenc.jpg',
  },
  {
    type: 'DINNER',
    itemid: 4,
    name: 'Millet roti 2 with salad',
    cal: ' 175 cal',
    carb: ' 29g',
    protein: ' 7g',
    fat: '4g',
    path: 'miletr.jpeg',
    path2: 'vsal.jpeg',
  },

  {
    type: 'SNACK',
    itemid: 1,
    name: '1 Apple with 1 glass Coconut water',
    cal: ' 98 cal',
    carb: ' 34g',
    protein: ' 2g',
    fat: '0.48g',
    path: 'asal.jpg',
    path2: 'cwater.jpg',
  },
  {
    type: 'SNACK',
    itemid: 2,
    name: 'Steamed corn ½ cup with 1 glass of lime juice without sugar',
    cal: ' 90 cal',
    carb: ' 21g',
    protein: '4g',
    fat: '1g',
    path: 'corn.jpeg',
    path2: 'lime.jpeg',
  },
  {
    type: 'SNACK',
    itemid: 3,
    name: 'Chicken soup - 1cup and wheat biscuits',
    cal: ' 100 cal',
    carb: ' 12g',
    protein: ' 7g',
    fat: '2.5g',
    path: 'cs.jpeg',
    path2: 'wheatbisc.jpg',
  },
  {
    type: 'SNACK',
    itemid: 4,
    name: 'Avocado with Almonds and Peanut',
    cal: ' 330 cal',
    carb: ' 14g',
    protein: '10g',
    fat: '15g',
    path: 'ava.jpg',
    path2: 'chana.jpeg',
  },
];
module.exports = diabetes;
